# -*- coding: utf-8 -*-
"""Anomaly Detection & Time Series |  Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjiAAuQ9YbQy-LhhcI7Qg4kp72eGxcJK

# **Assignment: Anomaly Detection & Time Series**

---

## **Question 1: What is Anomaly Detection? Explain its types**

### **Answer:**

**Anomaly Detection** is the process of identifying unusual patterns or observations that deviate significantly from normal behavior.

### **Types of Anomalies:**

### **1. Point Anomalies**

* A single data point is abnormal
* **Example:** A sudden spike in electricity usage

---

### **2. Contextual Anomalies**

* Anomaly depends on context (time, location)
* **Example:** High temperature in winter

---

### **3. Collective Anomalies**

* A group of data points behaves abnormally
* **Example:** Continuous drop in server performance

---

## **Question 2: Isolation Forest vs DBSCAN vs LOF**

### **Answer:**

| Method                         | Approach                    | Use Case                   |
| ------------------------------ | --------------------------- | -------------------------- |
| **Isolation Forest**           | Randomly isolates anomalies | Large datasets             |
| **DBSCAN**                     | Density-based clustering    | Detecting clusters + noise |
| **LOF (Local Outlier Factor)** | Compares local density      | Detecting local anomalies  |

### **Summary:**

* Isolation Forest → Fast, scalable
* DBSCAN → Good for spatial data
* LOF → Good for local density variations

---

## **Question 3: Components of Time Series**

### **Answer:**

### **1. Trend**

* Long-term increase/decrease
* Example: Rising population

---

### **2. Seasonality**

* Regular repeating patterns
* Example: Sales increase during festivals

---

### **3. Cyclical**

* Irregular long-term fluctuations
* Example: Economic cycles

---

### **4. Residual (Noise)**

* Random variation
* Example: Sudden unpredictable changes

---

## **Question 4: Stationarity**

### **Answer:**

A time series is **stationary** if:

* Mean is constant
* Variance is constant
* No trend or seasonality

---

### **Testing Stationarity:**

* Augmented Dickey-Fuller (ADF) test

---

### **Transformations:**

1. Differencing
2. Log transformation
3. Seasonal decomposition

---

## **Question 5: AR, MA, ARIMA, SARIMA, SARIMAX**

### **Answer:**

| Model                   | Description                     |
| ----------------------- | ------------------------------- |
| **AR (AutoRegressive)** | Uses past values                |
| **MA (Moving Average)** | Uses past errors                |
| **ARIMA**               | Combines AR + MA + differencing |
| **SARIMA**              | ARIMA + seasonality             |
| **SARIMAX**             | SARIMA + external variables     |

---

## **Question 6: Time Series Decomposition**

### **Answer:**

```python id="ts1"
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose

# Load dataset
df = pd.read_csv("AirPassengers.csv", parse_dates=['Month'], index_col='Month')

# Decompose
result = seasonal_decompose(df['Passengers'], model='multiplicative')

# Plot
result.plot()
plt.show()
```

### **Output:**

* Trend graph
* Seasonal pattern
* Residual noise

---

## **Question 7: Isolation Forest for Anomaly Detection**

### **Answer:**

```python id="iso1"
from sklearn.ensemble import IsolationForest
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("taxi_fare.csv")

X = df[['fare_amount', 'trip_distance']]

model = IsolationForest(contamination=0.05)
df['anomaly'] = model.fit_predict(X)

# Plot
plt.scatter(df['fare_amount'], df['trip_distance'], c=df['anomaly'])
plt.xlabel("Fare")
plt.ylabel("Distance")
plt.show()
```

---

## **Question 8: SARIMA Forecasting**

### **Answer:**

```python id="sarima1"
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt

df = pd.read_csv("AirPassengers.csv", parse_dates=['Month'], index_col='Month')

model = SARIMAX(df['Passengers'], order=(1,1,1), seasonal_order=(1,1,1,12))
results = model.fit()

forecast = results.forecast(steps=12)

plt.plot(df['Passengers'], label='Actual')
plt.plot(forecast, label='Forecast')
plt.legend()
plt.show()
```

---

## **Question 9: Local Outlier Factor (LOF)**

### **Answer:**

```python id="lof1"
from sklearn.neighbors import LocalOutlierFactor
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("taxi_fare.csv")

X = df[['fare_amount', 'trip_distance']]

lof = LocalOutlierFactor(n_neighbors=20)
df['anomaly'] = lof.fit_predict(X)

plt.scatter(df['fare_amount'], df['trip_distance'], c=df['anomaly'])
plt.show()
```

---

## **Question 10: Real-Time Power Grid Workflow**

### **Answer:**

### **1. Anomaly Detection:**

* Use **Isolation Forest** for real-time detection
* Detect spikes/drops in energy consumption

---

### **2. Time Series Model:**

* Use **SARIMAX**
* Handles:

  * Seasonality (daily patterns)
  * External variables (weather, region)

---

### **3. Validation & Monitoring:**

* Use rolling forecasts
* Metrics:

  * RMSE
  * MAE
* Monitor drift over time

---

### **4. Business Impact:**

* Prevent power outages
* Optimize energy distribution
* Reduce operational costs

---

### **Python Code (Workflow):**

```python id="finalts1"
from sklearn.ensemble import IsolationForest
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Anomaly detection
iso = IsolationForest()
anomalies = iso.fit_predict(X)

# Forecasting
model = SARIMAX(y, order=(1,1,1), seasonal_order=(1,1,1,12))
result = model.fit()

forecast = result.forecast(steps=10)
print(forecast)
```
"""

